%...............................................
% Author: Haoxiang Huang, MSc CSP, IC. 
% Date: 07-Dec-2023.
% This is the Task4 design for the ACT CW PartA
%...............................................