%...............................................
% Author: Haoxiang Huang, MSc CSP, IC. 
% Date: 08-Dec-2023.
% This is the Task2 design for the ACT CW PartB
%...............................................

